language: cpp

os:
  - linux
  - osx

sudo: true

compiler:
  - gcc

env:
  matrix:
    - COMPILER=g++-4.9 CCOMPILER=gcc-4.9
    - COMPILER=g++-5 CCOMPILER=gcc-5
    - COMPILER=clang++-3.6 CCOMPILER=clang-3.6
    - COMPILER=clang++-3.8 CCOMPILER=clang-3.8

matrix:
  allow_failures:
    - env: COMPILER=clang++-3.6 CCOMPILER=clang-3.6
    - os: osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - george-edison55-precise-backports
    packages:
      - g++-4.9
      - g++-5
      - clang-3.6
      - clang-3.8
      - cmake
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libglew-dev
      - freeglut3-dev
      - libxmu-dev
      - libxi-dev
      - libdevil-dev

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2_ttf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glew    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install freeglut; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install devil   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linus" ]]; export CXX=$COMPILER CC=$CCOMPILER; fi
  - cmake --version
  - mkdir build
  - cd build
  - cmake -LAH ..

script:
  - make VERBOSE=1