language: cpp

sudo: true

compiler:
  - gcc

env:
  matrix:
    - COMPILER=g++-4.9 CCOMPILER=gcc-4.9
    - COMPILER=g++-5 CCOMPILER=gcc-5
    - COMPILER=clang++-3.6 CCOMPILER=clang-3.6
    - COMPILER=clang++-3.8 CCOMPILER=clang-3.8

matrix:
  allow_failures:
    - env: COMPILER=clang++-3.6 CCOMPILER=clang-3.6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - george-edison55-precise-backports
    packages:
      - g++-4.9
      - g++-5
      - clang-3.6
      - clang-3.8
      - valgrind
      - python-pip
      - python-yaml
      - cmake
      - cmake-data
      - libsdl2-dev
      - libsdl2-ttf-dev
      - libsdl2-mixer-dev
      - libglew-dev
      - freeglut3-dev
      - libxmu-dev
      - libxi-dev
      - libdevil-dev

before_script:
  - export CXX=$COMPILER CC=$CCOMPILER
  - cmake --version
  - mkdir build
  - cd build
  - cmake -LAH ..

script:
  - make VERBOSE=1